name: Build Docker Image for RunPod

on:
  push:
    branches: [main]
  release:
    types: [created]

env:
  GAR_LOCATION: us-central1
  GAR_REPOSITORY: talking-head-registry
  PROJECT_ID: jay-dhanwant-experiments
  IMAGE_NAME: runpod-nvidia-smi

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Configure Docker for GAR
      run: |
        gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev
    
    - name: Build and push to GAR
      run: |
        IMAGE_URL="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}"
        
        # Build and tag image
        docker buildx build --platform linux/amd64 \
          -t "${IMAGE_URL}:latest" \
          -t "${IMAGE_URL}:${{ github.sha }}" \
          --push .
        
        echo "✅ Built and pushed: ${IMAGE_URL}:${{ github.sha }}"
        echo "✅ Built and pushed: ${IMAGE_URL}:latest"
    
    - name: Create deployment info
      run: |
        echo "## 🚀 RunPod Deployment Ready" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Docker Image**: \`${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Next Steps:" >> $GITHUB_STEP_SUMMARY
        echo "1. Go to [RunPod Console](https://www.runpod.io/console/serverless)" >> $GITHUB_STEP_SUMMARY
        echo "2. Click **New Endpoint**" >> $GITHUB_STEP_SUMMARY
        echo "3. Select **Custom Image**" >> $GITHUB_STEP_SUMMARY
        echo "4. Use the image URL above" >> $GITHUB_STEP_SUMMARY
        echo "5. Configure GPU settings" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Test with:" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
        echo "curl -X POST \"https://api.runpod.ai/v2/YOUR_ENDPOINT_ID/runsync\" \\" >> $GITHUB_STEP_SUMMARY
        echo "  -H \"Content-Type: application/json\" \\" >> $GITHUB_STEP_SUMMARY
        echo "  -d '{\"input\": {}}'" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY